services:
  azure-vote-back:
    image: docker.io/bitnami/redis:7.4
    container_name: azure-vote-back
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "6379:6379"

  azure-vote-front:
    build: ./azure-vote
    image: azure-vote-front:v1
    container_name: azure-vote-front
    depends_on:
      - azure-vote-back
    environment:
      REDIS: azure-vote-back
    ports:
      - "5000:5000"
